
    {
    "City": "MTY",
    "Buses":[
                {
                  "Color1" : "#08A5E8",
                  "ColorTxt" : "#08A5E8",
                  "PriceG" : 12,
                  "PriceS" : 6.67,
                  "TransitSeconds" : 0,
                  "SecLastRefresh" : 0,
                  "Route" : 218,
                  "ID" : 1,
                  "Way" : 1,
                  "WayName" : "Rosita Azteca",
                  "Lon" : -100.340673,
                  "Color2" : "#FFFFFF",
                  "PriceN" : 10.06,
                  "Lat" : 25.686719,
                  "SpeedKmHr" : 0,
                  "Status" : 1
                }, 
                {
                  "Color1" : "#59035D",
                  "ColorTxt" : "#FFFFFF",
                  "PriceG" : 12,
                  "PriceS" : 6.67,
                  "TransitSeconds" : 0,
                  "SecLastRefresh" : 0,
                  "Route" : 209,
                  "ID" : 2,
                  "Way" : 1,
                  "WayName" : "Escobedo",
                  "Lon" : -100.323850,
                  "Color2" : "#2D6315",
                  "PriceN" : 10.06,
                  "Lat" : 25.686719,
                  "SpeedKmHr" : 0,
                  "Status" : 1
                }, 
                {
                  "Color1" : "#EE3E02",
                  "ColorTxt" : "#FFFFFF",
                  "PriceG" : 12,
                  "PriceS" : 6.67,
                  "TransitSeconds" : 0,
                  "SecLastRefresh" : 0,
                  "Route" : 219,
                  "ID" : 3,
                  "Way" : 1,
                  "WayName" : "Churubusco",
                  "Lon" : -100.294667,
                  "Color2" : "#016644",
                  "PriceN" : 10.06,
                  "Lat" : 25.683625,
                  "SpeedKmHr" : 0,
                  "Status" : 1
                 }, 
                {
                  "Color1" : "#ACA59B",
                  "ColorTxt" : "#FFFFFF",
                  "PriceG" : 12,
                  "PriceS" : 6.67,
                  "TransitSeconds" : 0,
                  "SecLastRefresh" : 0,
                  "Route" : 1,
                  "ID" : 4,
                  "Way" : 1,
                  "WayName" : "Central",
                  "Lon" : -100.294667,
                  "Color2" : "#046C87",
                  "PriceN" : 10.06,
                  "Lat" : 25.683625,
                  "SpeedKmHr" : 0,
                  "Status" : 1
                 }, 
                {
                  "Color1" : "#ACA59B",
                  "ColorTxt" : "#FFFFFF",
                  "PriceG" : 12,
                  "PriceS" : 6.67,
                  "TransitSeconds" : 0,
                  "SecLastRefresh" : 0,
                  "Route" : 1,
                  "ID" : 5,
                  "Way" : 2,
                  "WayName" : "Directo",
                  "Lon" : -100.294667,
                  "Color2" : "#046C87",
                  "PriceN" : 10.06,
                  "Lat" : 25.683625,
                  "SpeedKmHr" : 0,
                  "Status" : 1
                 }, 
                {
                  "Color1" : "#C65712",
                  "ColorTxt" : "#595959",
                  "PriceG" : 12,
                  "PriceS" : 6.67,
                  "TransitSeconds" : 0,
                  "SecLastRefresh" : 0,
                  "Route" : 2,
                  "ID" : 6,
                  "Way" : 1,
                  "WayName" : "",
                  "Lon" : -100.294667,
                  "Color2" : "#AB320F",
                  "PriceN" : 10.06,
                  "Lat" : 25.683625,
                  "SpeedKmHr" : 0,
                  "Status" : 1
                 }, 
                {
                  "Color1" : "#88C6ED",
                  "ColorTxt" : "#DC414F",
                  "PriceG" : 12,
                  "PriceS" : 6.67,
                  "TransitSeconds" : 0,
                  "SecLastRefresh" : 0,
                  "Route" : 4,
                  "ID" : 7,
                  "Way" : 1,
                  "WayName" : "Circunvalacion",
                  "Lon" : -100.294667,
                  "Color2" : "#FFFFFF",
                  "PriceN" : 10.06,
                  "Lat" : 25.683625,
                  "SpeedKmHr" : 0,
                  "Status" : 1
                 }, 
                {
                  "Color1" : "#88C6ED",
                  "ColorTxt" : "#DC414F",
                  "PriceG" : 12,
                  "PriceS" : 6.67,
                  "TransitSeconds" : 0,
                  "SecLastRefresh" : 0,
                  "Route" : 5,
                  "ID" : 8,
                  "Way" : 1,
                  "WayName" : "Estanzuela",
                  "Lon" : -100.294667,
                  "Color2" : "#FFFFFF",
                  "PriceN" : 10.06,
                  "Lat" : 25.683625,
                  "SpeedKmHr" : 0,
                  "Status" : 1
                 }, 
                {
                  "Color1" : "#C65712",
                  "ColorTxt" : "#595959",
                  "PriceG" : 12,
                  "PriceS" : 6.67,
                  "TransitSeconds" : 0,
                  "SecLastRefresh" : 0,
                  "Route" : 7,
                  "ID" : 9,
                  "Way" : 1,
                  "WayName" : "Escobedo",
                  "Lon" : -100.294667,
                  "Color2" : "#AB320F",
                  "PriceN" : 10.06,
                  "Lat" : 25.683625,
                  "SpeedKmHr" : 0,
                  "Status" : 1
                 }, 
                {
                  "Color1" : "#C65712",
                  "ColorTxt" : "#595959",
                  "PriceG" : 12,
                  "PriceS" : 6.67,
                  "TransitSeconds" : 0,
                  "SecLastRefresh" : 0,
                  "Route" : 7,
                  "ID" : 10,
                  "Way" : 2,
                  "WayName" : "Real de Palmas",
                  "Lon" : -100.294667,
                  "Color2" : "#AB320F",
                  "PriceN" : 10.06,
                  "Lat" : 25.683625,
                  "SpeedKmHr" : 0,
                  "Status" : 1
                 }, 
                {
                  "Color1" : "#C65712",
                  "ColorTxt" : "#595959",
                  "PriceG" : 12,
                  "PriceS" : 6.67,
                  "TransitSeconds" : 0,
                  "SecLastRefresh" : 0,
                  "Route" : 7,
                  "ID" : 11,
                  "Way" : 3,
                  "WayName" : "Villas de Alcala",
                  "Lon" : -100.294667,
                  "Color2" : "#AB320F",
                  "PriceN" : 10.06,
                  "Lat" : 25.683625,
                  "SpeedKmHr" : 0,
                  "Status" : 1
                 }, 
                {
                  "Color1" : "#C39815",
                  "ColorTxt" : "#5e5e5e",
                  "PriceG" : 12,
                  "PriceS" : 6.67,
                  "TransitSeconds" : 0,
                  "SecLastRefresh" : 0,
                  "Route" : 6,
                  "ID" : 12,
                  "Way" : 1,
                  "WayName" : "Larga",
                  "Lon" : -100.294667,
                  "Color2" : "#222222",
                  "PriceN" : 10.06,
                  "Lat" : 25.683625,
                  "SpeedKmHr" : 0,
                  "Status" : 1
                 }, 
                {
                  "Color1" : "#C65712",
                  "ColorTxt" : "#595959",
                  "PriceG" : 12,
                  "PriceS" : 6.67,
                  "TransitSeconds" : 0,
                  "SecLastRefresh" : 0,
                  "Route" : 9,
                  "ID" : 13,
                  "Way" : 1,
                  "WayName" : "Fomerrey 35 Santa Martha",
                  "Lon" : -100.294667,
                  "Color2" : "#AB320F",
                  "PriceN" : 10.06,
                  "Lat" : 25.683625,
                  "SpeedKmHr" : 0,
                  "Status" : 1
                 }, 
                {
                  "Color1" : "#C65712",
                  "ColorTxt" : "#595959",
                  "PriceG" : 12,
                  "PriceS" : 6.67,
                  "TransitSeconds" : 0,
                  "SecLastRefresh" : 0,
                  "Route" : 10,
                  "ID" : 14,
                  "Way" : 1,
                  "WayName" : "Solidaridad Centro",
                  "Lon" : -100.294667,
                  "Color2" : "#AB320F",
                  "PriceN" : 10.06,
                  "Lat" : 25.683625,
                  "SpeedKmHr" : 0,
                  "Status" : 1
                 }, 
                {
                  "Color1" : "#C39815",
                  "ColorTxt" : "#B12222",
                  "PriceG" : 12,
                  "PriceS" : 6.67,
                  "TransitSeconds" : 0,
                  "SecLastRefresh" : 0,
                  "Route" : 11,
                  "ID" : 15,
                  "Way" : 1,
                  "WayName" : "San Bernabe",
                  "Lon" : -100.294667,
                  "Color2" : "#222222",
                  "PriceN" : 10.06,
                  "Lat" : 25.683625,
                  "SpeedKmHr" : 0,
                  "Status" : 1
                 }, 
                {
                  "Color1" : "#C39815",
                  "ColorTxt" : "#B12222",
                  "PriceG" : 12,
                  "PriceS" : 6.67,
                  "TransitSeconds" : 0,
                  "SecLastRefresh" : 0,
                  "Route" : 12,
                  "ID" : 16,
                  "Way" : 1,
                  "WayName" : "Planta",
                  "Lon" : -100.294667,
                  "Color2" : "#222222",
                  "PriceN" : 10.06,
                  "Lat" : 25.683625,
                  "SpeedKmHr" : 0,
                  "Status" : 1
                 }, 
                {
                  "Color1" : "#FFFFFF",
                  "ColorTxt" : "#222222",
                  "PriceG" : 12,
                  "PriceS" : 6.67,
                  "TransitSeconds" : 0,
                  "SecLastRefresh" : 0,
                  "Route" : 13,
                  "ID" : 17,
                  "Way" : 1,
                  "WayName" : "Agropecuaria",
                  "Lon" : -100.294667,
                  "Color2" : "#EEEEEE",
                  "PriceN" : 10.06,
                  "Lat" : 25.683625,
                  "SpeedKmHr" : 0,
                  "Status" : 1
                 }, 
                {
                  "Color1" : "#FFFFFF",
                  "ColorTxt" : "#222222",
                  "PriceG" : 12,
                  "PriceS" : 6.67,
                  "TransitSeconds" : 0,
                  "SecLastRefresh" : 0,
                  "Route" : 13,
                  "ID" : 18,
                  "Way" : 2,
                  "WayName" : "Metrobus",
                  "Lon" : -100.294667,
                  "Color2" : "#EEEEEE",
                  "PriceN" : 10.06,
                  "Lat" : 25.683625,
                  "SpeedKmHr" : 0,
                  "Status" : 1
                 },
                 {
                  "Color1" : "#FFFFFF",
                  "ColorTxt" : "#222222",
                  "PriceG" : 12,
                  "PriceS" : 6.67,
                  "TransitSeconds" : 0,
                  "SecLastRefresh" : 0,
                  "Route" : 505,
                  "ID" : 16,
                  "Way" : 1,
                  "WayName" : "Circuito Valle A",
                  "Lon" : -100.294667,
                  "Color2" : "#FFFFFF",
                  "PriceN" : 10.06,
                  "Lat" : 25.683625,
                  "SpeedKmHr" : 0,
                  "Status" : 1
                 }
              ]
       }
